streams:
  # Direct USB Camera Access (V4L2)
  hunter_cam: v4l2:device?video=/dev/video0&input_format=yuyv422&video_size=640x480&framerate=30

api:
  listen: ":1984" # HTTP API Port
  origin: "*"     # CORS allow

srtp:
  listen: ":8443" # WebRTC Port

webrtc:
  listen: ":8555"
