# Hunter Teleop System Configuration

# Launch Configuration (These determine which nodes are started)
launch_params:
  use_sim: true             # true: Mock Robot, false: Real Hardware
  use_remote_teleop: true   # true: Enable UDP/TwistMux/WebRTC

# Node Configuration (Passed to nodes)
udp_receiver_node:
  ros__parameters:
    port: 5000
    timeout: 0.5
    max_linear_vel: 1.5
    max_angular_vel: 0.5
